# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

ENVIRONMENT:
  MAX_CONTEXT_LENGTH: 16
  VISUAL_BUDGET: 4 # actual visual budget + number of agents
  MAX_QUERY_LENGTH: 32
SIMULATOR:
  USE_RENDERED_OBSERVATIONS: True
  SCENE_DATASET: "mp3d"
  RENDERED_OBSERVATIONS: "data/scene_observations/"
  # local ego maps per scene per receiver node per rotation angle, size = 31 x 31 mapped at a resolution of 0.1 m
  RENDERED_LOCAL_EGO_OCC_MAPS_DIR: "data/gt_topdown_maps/occupancy/localEgoMaps_perScenePerRRotn/mp3d/mp_sz31_scl01" 
  # target local ego maps per scene per receiver node per rotation angle, size = 64 x 64 mapped at a resolution of 0.1 m, crops taken from stitching 51 x 51  size local ego maps 
  RENDERED_GT_GLOBAL_CANONICAL_OCC_MAP_EGO_CROP_N_ROTS_DIR: "data/gt_topdown_maps/occupancy/stitchedEgoMaps_egoCropRot_perScenePerRRotn/mp3d/mp_sz64_scl01_srcEgLclMp_sz51"
  GRID_SIZE: 1.0 
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0

  AUDIO:
    META_DIR: "data/metadata/mp3d" 
    RIR_DIR: "data/ambisonic_rirs/mp3d" 
    RIR_SAMPLING_RATE:  16000 
    HOP_LENGTH: 133 
    N_FFT: 511 
    WIN_LENGTH: 400
    MAX_VALID_IMPULSE_LENGTH_AFTER_REMOVING_LEADING_ZEROS: 34065 
    ANECHOIC_AUDIO_SLICE_LENGTH: 3.0
    ANECHOIC_DIR: "data/sounds/libri100Classes/heard_16k_rmsNorm400"
    VAL_UNHEARD_ANECHOIC_DIR: "data/sounds/libri100Classes/heard_16k_rmsNorm400"
    TEST_UNHEARD_ANECHOIC_DIR: "data/sounds/libri100Classes/heard_16k_rmsNorm400" # heard_16k_rmsNorm400, testUnheard_16k_rmsNorm400
    ANECHOIC_AUDIO_TARGET_RMS: 400

  LOCAL_MAP:
    SIZE: 31
    SCALE: 0.1
    AGENT_POSITION: [0, 1.25, 0]
    HEIGHT_THRESH: [0.2, 1.5]
    WIDTH_DEPTH_IMG: 128
    HEIGHT_DEPTH_IMG: 128
    HFOV_DEPTH_IMG: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 67.16327
    NORMALIZE_DEPTH_IMG: False

  ALL_AGENTS:
    NUM: 2 

  TYPE: "HabitatSimAudioEnabledMultiAgentActiveMapping" 
  ACTION_SPACE_CONFIG: "chat2map"

TASK:
  TYPE: chat2map

  SENSORS: ["CONTEXT_RGB_SENSOR", "CONTEXT_EGO_LOCAL_MAP_SENSOR",
            "CONTEXT_VIEW_POSE_SENSOR", "PREV_CONTEXT_VIEW_MASK_SENSOR",
            "CONTEXT_SELF_AUDIO_SENSOR", "CONTEXT_OTHER_AUDIO_SENSOR",
            "CONTEXT_OTHER_AUDIO_POSE_SENSOR", "CONTEXT_AUDIO_MASK_SENSOR",
            "ALL_CONTEXT_AUDIO_MASK_SENSOR", "CONTEXT_IDX_SENSOR",
            "QUERY_GT_GLOB_CAN_MAP_EGO_CROP_SENSOR",
            "QUERY_GT_GLOB_CAN_MAP_EGO_CROP_EXPLORED_PART_MASK_SENSOR",
            "QUERY_MASK_SENSOR", "ALL_QUERY_MASK_SENSOR"
            ]   

  CONTEXT_RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  CONTEXT_DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    MIN_DEPTH: 0.0
    MAX_DEPTH: 67.16327 
    NORMALIZE_DEPTH: True

  CONTEXT_EGO_LOCAL_MAP_SENSOR:
    SIZE: 31
    NUM_CHANNELS: 2

  QUERY_GT_GLOB_CAN_MAP_EGO_CROP_SENSOR:
    SIZE: 64
    NUM_CHANNELS: 2
    SCALE: 0.1

  CONTEXT_STITCHED_EGO_LOCAL_MAP_SENSOR:
    SIZE: 1284 

  MEASUREMENTS: []
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP"]

DATASET:
  TYPE: "chat2map"
  SPLIT: "train_rand_20steps_2agents_100attemptsOtherAgents_3.0eucDistThresh_noTrajOverlap"
  VERSION: 'v1_redundanciesRemoved'
  CONTENT_SCENES: ["*"]
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/mp3d/{version}/w_audio/{split}/{split}.json.gz"
